Budget/Budget/Entities/Bill.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Budget.Entities
{
    public class Bill
    {
        public int BillId { get; set; }
        [DisplayName("Amount Due")]
        public decimal AmountDue { get; set; }
        [DisplayName("Amount Paid")]
        public decimal AmountPaid { get; set; }
        [DisplayName("Amount Owed")]
        public decimal AmountOwed { get; set; }
        [DisplayName("Date Due")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DateDue { get; set; }
        [DisplayName("Date Paid")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}",ApplyFormatInEditMode = true)]
        public DateTime DatePaid { get; set; }
        [DisplayName("Bill For")]
        public string MonthYear { get; set; }
        public int CompanyId { get; set; }
        public virtual Company Company { get; set; } 
    }
}

Budget/Budget/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Budget.DAL;
using Budget.Entities;
using System.Globalization;
using System.Reflection;
using System.Web.Script.Serialization;
using Budget.Utilities;
using Newtonsoft.Json;

namespace Budget
{
    public class BillsController : Controller
    {
        private BudgetContext db = new BudgetContext();

        // GET: Bills
        public ActionResult Index(string searchMonthYear)
        {
            string monthYear = searchMonthYear == null
                ? $"{DateTime.Now.Month}/{DateTime.Now.Year}"
                : searchMonthYear;
            IEnumerable<Bill> model = db.Bills.Where(b=>b.MonthYear == monthYear).ToList();
            decimal totalDue = model.Sum(b => b.AmountDue);
            decimal totalPaid = model.Sum(b => b.AmountPaid);
            decimal totalOwed = model.Sum(b => b.AmountOwed);
            ViewBag.totalDue = totalDue;
            ViewBag.totalPaid = totalPaid;
            ViewBag.totalOwed = totalOwed;
            ViewBag.monthYear = DateTime.Parse(monthYear).ToString("MMMM yyyy");

            ViewBag.ddlSearchMonthYear = GetDdlSearchMonthYear(monthYear);

            return View(model);
        }

        private List<SelectListItem> GetDdlSearchMonthYear(string monthYear)
        {
            var billMonthYears = db.Bills.Select(b => b.MonthYear).Distinct().ToList();
            List<DateTime> dateMonthYears = new List<DateTime>();
            foreach (var item in billMonthYears)
            {
                dateMonthYears.Add(DateTime.Parse(item));
            }
            List<SelectListItem> ddlSearchMonthYear = new List<SelectListItem>();
            var firstMonthYear = dateMonthYears.OrderBy(d => d.Date).FirstOrDefault();
            var curYear = DateTime.Today.Year;
            var curMonth = DateTime.Today.Month;
            int year = firstMonthYear.Year;
            int month = firstMonthYear.Month;
            while (year < DateTime.Now.AddYears(1).Year)
            {
                while (month < 13)
                {
                    var item = new SelectListItem
                    {
                        Value = $"{month.ToString()}/{year.ToString()}",
                        Text = $"{Utilities.Get.MonthName(month)} {year.ToString()}"
                    };
                    ddlSearchMonthYear.Add(item);
                    month++;
                    if (month > curMonth + 3 && year == curYear)
                    {
                        break;
                    }
                }
                month = 1;
                year++;
            }
            ddlSearchMonthYear.First(s => s.Value == monthYear).Selected = true;
            return ddlSearchMonthYear;
        }

        // GET: Bills/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // GET: Bills/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BillId,AmountDue,AmountPaid,AmountOwed,DateDue,DatePaid,MonthYear,CompanyId")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                db.Bills.Add(bill);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bill);
        }

        // GET: Bills/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // POST: Bills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BillId,AmountDue,AmountPaid,AmountOwed,DateDue,DatePaid,MonthYear")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bill).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bill);
        }

        // GET: Bills/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // POST: Bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bill bill = db.Bills.Find(id);
            db.Bills.Remove(bill);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Update")]
        public ActionResult UpdateBillItem(int billId, string billItem, string billItemText)
        {
            string itemName = string.Empty;
            Bill bill = db.Bills.Find(billId);
            if (bill == null)
            {
                return HttpNotFound();
            }
            switch (billItem)
            {
                case "AmountDue":
                    bill.AmountDue = decimal.Parse(billItemText);
                    itemName = Reflection.GetPropertyDisplayName<Bill>(i => i.AmountDue);
                    break;
                case "AmountPaid":
                    bill.AmountPaid = decimal.Parse(billItemText);
                    itemName = Reflection.GetPropertyDisplayName<Bill>(i => i.AmountPaid);
                    break;
                case "AmountOwed":
                    bill.AmountOwed = decimal.Parse(billItemText);
                    itemName = Reflection.GetPropertyDisplayName<Bill>(i => i.AmountOwed);
                    break;
                case "DateDue":
                    bill.DateDue = DateTime.Parse(billItemText);
                    itemName = Reflection.GetPropertyDisplayName<Bill>(i => i.DateDue);
                    break;
                case "DatePaid":
                    bill.DatePaid = DateTime.Parse(billItemText);
                    itemName = Reflection.GetPropertyDisplayName<Bill>(i => i.DatePaid);
                    break;
                default:
                    return HttpNotFound();
            }
            db.Entry(bill).State = EntityState.Modified;
            db.SaveChanges();
            string monthYear = bill.MonthYear;
            IEnumerable<Bill> model = db.Bills.Where(b => b.MonthYear == monthYear).ToList();
            decimal totalDue = model.Sum(b => b.AmountDue);
            decimal totalPaid = model.Sum(b => b.AmountPaid);
            decimal totalOwed = model.Sum(b => b.AmountOwed);
            ViewBag.totalDue = totalDue;
            ViewBag.totalPaid = totalPaid;
            ViewBag.totalOwed = totalOwed;
            return PartialView("_BillsTableData", model);
        }

        [HttpPost, ActionName("PopulateBills")]
        public ActionResult PopulateBills(string monthYear)
        {
            if (string.IsNullOrEmpty(monthYear))
            {
                return HttpNotFound();
            }

            var dMonthYear = DateTime.Parse(monthYear);
            var pMonthYear = dMonthYear.AddMonths(-1).ToString("M/yyyy");

            List<Bill> pModel = db.Bills.Where(b => b.MonthYear == pMonthYear).ToList();
            foreach (var item in pModel)
            {
                Bill bill = new Bill();
                bill.AmountDue = item.AmountDue;
                bill.DateDue = item.DateDue.AddMonths(1);
                bill.CompanyId = item.CompanyId;
                bill.MonthYear = dMonthYear.ToString("M/yyyy");
                bill.DatePaid = DateTime.Parse("1/1/1900");
                bill.AmountOwed = 0;
                bill.AmountPaid = 0;
                db.Bills.Add(bill);
                db.SaveChanges();
            }
            

            IEnumerable<Bill> model = db.Bills.Where(b => b.MonthYear == monthYear).ToList();
            decimal totalDue = model.Sum(b => b.AmountDue);
            decimal totalPaid = model.Sum(b => b.AmountPaid);
            decimal totalOwed = model.Sum(b => b.AmountOwed);
            ViewBag.totalDue = totalDue;
            ViewBag.totalPaid = totalPaid;
            ViewBag.totalOwed = totalOwed;
            return PartialView("_BillsTableData", model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Budget/Budget/Views/Bills/Create.cshtml
@model Budget.Entities.Bill

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bill</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AmountDue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmountDue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AmountDue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AmountPaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmountPaid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AmountPaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AmountOwed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmountOwed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AmountOwed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateDue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateDue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateDue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatePaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatePaid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatePaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MonthYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MonthYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MonthYear, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Budget/Budget/Views/Bills/Delete.cshtml
@model Budget.Entities.Bill

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bill</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AmountDue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountDue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountPaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountPaid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountOwed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountOwed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateDue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateDue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatePaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatePaid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MonthYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MonthYear)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Budget/Budget/Views/Bills/Details.cshtml
@model Budget.Entities.Bill

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Bill</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AmountDue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountDue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountPaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountPaid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountOwed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountOwed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateDue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateDue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatePaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatePaid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MonthYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MonthYear)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BillId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Budget/Budget/Views/Bills/Edit.cshtml
@model Budget.Entities.Bill

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bill</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BillId)

        <div class="form-group">
            @Html.LabelFor(model => model.AmountDue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmountDue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AmountDue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AmountPaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmountPaid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AmountPaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AmountOwed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmountOwed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AmountOwed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateDue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateDue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateDue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatePaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatePaid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatePaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MonthYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MonthYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MonthYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Budget/Budget/Views/Bills/Index.cshtml
@using System.Web.UI.WebControls
@model IEnumerable<Budget.Entities.Bill>

@{
    ViewBag.Title = "Index";
}

<form method="post" action="@Url.Action("Index", "Bills")">
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <h2>Bills for @ViewBag.monthYear</h2>
                <div class="statusUpdates"></div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 form-inline">
                <div class="date-button">
                    <select id="searchMonthYear" name="searchMonthYear" class="form-control">
                        @foreach (var x in ViewBag.ddlSearchMonthYear)
                        {
                            if (x.Selected)
                            {
                                @:<option value="@x.Value" Selected="Selected">@x.Text</option>
                            }
                            else
                            {
                                @:<option value="@x.Value">@x.Text</option>
                            }
                        }
                    </select>
                    <button id="btnSubmit" type="submit" class="btn btn-primary">Change Month</button>
                    @if (Model.Count() == 0)
                    {
                        <button id="btnPopulateBills" type="button" class="btn btn-primary">Populate Bills</button>
                    }
                </div>
            </div>
        </div>
    </div>
</form>
<div id="tableData" class="clickToEdit">
    @RenderPage("_BillsTableData.cshtml",Model)
</div>

@section scripts {

    <script src="~/Scripts/Bills/index.js"></script>
}

Budget/Budget/Views/Bills/_BillsTableData.cshtml
@model IEnumerable<Budget.Entities.Bill>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Company.Name)
        </th>
        <th class="text-right">
            @Html.DisplayNameFor(model => model.AmountDue)
        </th>
        <th class="text-right">
            @Html.DisplayNameFor(model => model.AmountPaid)
        </th>
        <th class="text-right">
            @Html.DisplayNameFor(model => model.AmountOwed)
        </th>
        <th class="text-right">
            @Html.DisplayNameFor(model => model.DateDue)
        </th>
        <th class="text-right">
            @Html.DisplayNameFor(model => model.DatePaid)
        </th>
        <th class="text-center">@Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-default" })</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Company.Name)
            </td>
            <td class="text-right" data-bill-id="@item.BillId" data-bill-item="AmountDue">
                <span>@Html.DisplayFor(modelItem => item.AmountDue)</span>
            </td>
            <td class="text-right" data-bill-id="@item.BillId" data-bill-item="AmountPaid">
                <span>@Html.DisplayFor(modelItem => item.AmountPaid)</span>
            </td>
            <td class="text-right" data-bill-id="@item.BillId" data-bill-item="AmountOwed">
                <span>@Html.DisplayFor(modelItem => item.AmountOwed)</span>
            </td>
            <td class="text-right" data-bill-id="@item.BillId" data-bill-item="DateDue">
                <span>@Html.DisplayFor(modelItem => item.DateDue)</span>
            </td>
            <td class="text-right" data-bill-id="@item.BillId" data-bill-item="DatePaid">
                <span>@Html.DisplayName(item.DatePaid.Equals(DateTime.Parse("1/1/1900")) ? "" : item.DatePaid.ToString("MM/dd/yyyy"))</span>
            </td>
            <td class="text-center">
                @Html.ActionLink("Edit", "Edit", new { id = item.BillId }, new { @class = "btn btn-default btn-xs" })
                @Html.ActionLink("Details", "Details", new { id = item.BillId }, new { @class = "btn btn-default btn-xs" })
                @Html.ActionLink("Delete", "Delete", new { id = item.BillId }, new { @class = "btn btn-default btn-xs" })
            </td>
        </tr>
    }
    <tr>
        <td>Total</td>
        <td class="text-right">@ViewBag.totalDue</td>
        <td class="text-right">@ViewBag.totalPaid</td>
        <td class="text-right">@ViewBag.totalOwed</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>

</table>